### PR TITLE
Delegate chart update() to chartist

### PR DESCRIPTION
**Pull request by vladmiller**
Instead of destroying chartist object and creating new instance on each update we can delegate update to the chartist library itself

### CODE REVIEW

**Comment by vladmiller** [comment]
I re-compiled the app and updated source as well. I already use this update

**Comment by fraserxu** [comment]
:+1:  Thanks a lot @vladmiller . I'll push a new version later.

**Comment by vladmiller** [comment]
Thank you

**Comment by fraserxu** [comment]
Pushed to v0.7.0

**Pull request merged**
