### PR TITLE
Update to React 15

### PR DESCRIPTION
**Pull request by joshgerdes**
Initial testing with the charts I have in use (Line and Bar) seem to work fine with the upgrade. I have not fully tested with all chartist features.

### CODE REVIEW

**Comment by jcblw** [comment]
I have also confirmed with one of my projects that the pie/donut chart are functioning with react 15.

**Comment by joshgerdes** [comment]
@fraserxu Could you please publish this minor update to npm when you get a chance?  Thanks!

**Comment by fraserxu** [comment]
@joshgerdes @jcblw Something like v15.0.0?

**Comment by jcblw** [comment]
I would say just a patch like in the PR would be fine since nothing internally changed beside the peer dep. So `v0.10.2`

**Comment by fraserxu** [comment]
Hmm @jcblw , that makes sense. I'm suggesting `v15.0.0` because that may indicate to user that this is following the version of React?

Yes, you are right, there's no changes in the code, the code could work for version other than `v15.0.0`.

**Comment by jcblw** [comment]
I would still say patch version is better its an easier update path for people looking to update to react 15.

Its `npm update react-chartist` rather then `npm install react-chartist@15`. Also libs like [react-redux](https://github.com/reactjs/react-redux) and [react-dnd](https://github.com/gaearon/react-dnd) only updated there patch versions. I think the 15 version thing is mostly for the `react-addon-` stuff that facebook maintains.

**Comment by fraserxu** [comment]
I just updated the `peerDependencies` to 

```JSON
"peerDependencies": {
  "react": "^0.14.0 || ^15.0.0-0"
}
```

Following https://github.com/reactjs/react-redux/commit/da106bd49269285565b759dcb6a28a3bca22eb4b

And published to `v0.10.2`, thanks @joshgerdes @jcblw

**Comment by jcblw** [comment]
no thank you @fraserxu

**Pull request merged**
