### PR TITLE
Add TypeScript definitions

### PR DESCRIPTION
**Pull request by Amwam**
This includes a TypeScript module definition, so that the library can be used with TypeScript.

I wasn't sure if I should submit the PR here, or add it to DefinitelyTyped. If you feel its not appropriate here, I can submit a PR there.

### CODE REVIEW

**Comment by davidsparkles** [comment]
@fraserxu I would really love to have some typescript support in react-chartist. Chartist is great.

**Comment by fraserxu** [comment]
Thanks @Amwam @davidsparkles Just publised to 

```
npm notice
npm notice 📦  react-chartist@0.13.3
npm notice === Tarball Contents ===
npm notice 1.3kB package.json
npm notice 997B  index.d.ts
npm notice 1.8kB index.js
npm notice 1.1kB LICENSE
npm notice 2.6kB README.md
npm notice 997B  dist/index.d.ts
npm notice 4.6kB dist/index.js
npm notice === Tarball Details ===
npm notice name:          react-chartist
npm notice version:       0.13.3
npm notice package size:  4.4 kB
npm notice unpacked size: 13.3 kB
npm notice shasum:        2a6f677bab45b3474c828b74ef244fc4fca08d0b
npm notice integrity:     sha512-lHA2JKy6S81/4[...]7w2fUCCUXkjBA==
npm notice total files:   7
npm notice
+ react-chartist@0.13.3
```

**Comment by Amwam** [comment]
Thank you!

**Comment by Benjamin-Dobell** [comment]
Just a heads up that these type definitions are quite inaccurate. There's several repeated typos e.g. `Chartit` instead of `Chartist`, that's actually not a huge issue though as in theory the types would still work. However, they don't because there are other issues like `responseOptions` instead of `responsiveOptions`. Also definitions like`ChartitGraphPieProps` aren't particularly useful as they're not enforced anywhere - the react component's props should presumably be a union of all the different chart props.

**Pull request merged**
